FROM public.ecr.aws/lambda/python:3.9

COPY requirements requirements
RUN pip3 install -r requirements/lambda.txt --target "${LAMBDA_TASK_ROOT}"

COPY . ${LAMBDA_TASK_ROOT}

ENV RELAY_API_CONFIG live

CMD ["app.lambda_handler"]

