version: '3.4'

services:
  app:
    build:
      context: ${PWD}
      dockerfile: docker/Dockerfile.live
    environment:
      RELAY_API_CONFIG: live
      RELAY_API_KEYS_VAULT_SECRET: relay-api-secret
      RELAY_API_KEYS_VAULT_TYPE: SECRETSMANAGER
    command: gunicorn -w 4 -b 0.0.0.0:8000 wsgi:app
    volumes:
      - ${PWD}:/usr/src/app
    ports:
      - "8000:8000"

