INVALID_ACTIVITY = "RELAY/INVALID_ACTIVITY"
# USER_ALREADY_EXISTS = "RELAY/USER_ALREADY_EXISTS"
# USER_NOT_EXISTS = "RELAY/USER_NOT_EXISTS"

# INVALID_CREDENTIALS = "RELAY/INVALID_CREDENTIALS"
# MISSING_PARAMETERS = "RELAY/MISSING_PARAMETERS"
# TOKEN_EXPIRED = "RELAY/TOKEN_EXPIRED"

# OTP_REQUIRED = "RELAY/OTP_REQUIRED"
# OTP_EXPIRED = "RELAY/OTP_EXPIRED"
# OTP_INVALID = "RELAY/OTP_INVALID"
# OTP_NOT_SETUP = "RELAY/OTP_NOT_SETUP"

# UNKNOWN_ERROR = "RELAY/UNKNOWN_ERROR"
# UNABLE_TO_UPDATE = "RELAY/UNABLE_TO_UPDATE"

# SESSION_EXPIRED = "RELAY/SESSION_EXPIRED"

# PASSWORD_FORBIDDEN = "RELAY/PASSWORD_FORBIDDEN"
